### ISSUE TITLE
Problems compilation shr

### ISSUE THREAD

**Issue by ccoqueiro** [troydhanson/fluxcap#1]
Hi,

I'd try to compile shr libray, but  this is occurring the following error:

Making all in src
make[1]: Entering directory `/opt/shr/src'
  CC     libshr_a-shr.o
shr.c: In function ‘shr_open’:
shr.c:571: error: ‘O_PATH’ undeclared (first use in this function)
shr.c:571: error: (Each undeclared identifier is reported only once
shr.c:571: error: for each function it appears in.)
make[1]: *** [libshr_a-shr.o] Error 1
make[1]: Leaving directory `/opt/shr/src'
make: *** [all-recursive] Error 1

Thanks

PS: I try to install in CENTOS 6.9

**Comment by troydhanson** [comment]
Hi, libshr requires kernel 2.6.39 or greater. So that is the problem, Centos 6.9 is a little too early. I have added a check into "configure" to inform the user in this situation.
