### ISSUE TITLE
libshr.so.0 No such file or directory

### ISSUE THREAD

**Issue by justcour** [troydhanson/fluxcap#4]
I started with a fresh install of CentOS 8 with internet access.  I cloned the libshr and fluxcap repos and have run through the install process in the fluxcap readme.  Everything appears to go through fine, but when I go to create my first ring buffer, I'm getting the following error:

`fluxcap: error while loading shared libraries: libshr.so.0: cannot open shared object file: No such file or directory`

I have the following files in /usr/local/lib/:

`libshr.a
libshr.la
libshr.so
libshr.so.0
libshr.so.0.0.0`

shr.h is in /usr/local/include/

Any fluxcap command gives me the same error.

**Comment by troydhanson** [comment]
Hi, this is due to /usr/local/lib being omitted from the system's default library search path. The solution is to add it using:

```
echo /usr/local/lib | sudo tee /etc/ld.so.conf.d/local.conf
sudo ldconfig
```

Afterward, you should find that fluxcap finds it.
